// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guqyxqpdmyakzntmnegh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cXl4cXBkbXlha3pudG1uZWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzkwMjEsImV4cCI6MjA1MzE1NTAyMX0.pUH7fh2q1rsFSYlUs5aK_UFnqL8R6-HbLY3_6-XB5EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);